### ISSUE TITLE
Custom Albums can't search for "name_romanized" key

### ISSUE THREAD

**Issue by MinecraftNight4** [MDMods/CustomAlbums#10]
**[+] Description:**
Recently I have noticed that when searching for certain songs that have the key "romanized_name", inside the game it doesn't work.

**[+] Game Info:**
- Muse Dash 4.3.0
- MelonLoader 0.6.1
- Custom Albums 4.0.3
- Mod Loaded:
	Cinema v1.2.0
	Headquarters v3.3.1
	PeroPeroSkip v1.0.0

**[+] Game Logs:**
[Latest.log](https://github.com/MDMods/CustomAlbums/files/15238590/Latest.log)

**[+] Resources:**

**Chart:**
[temp.zip](https://github.com/MDMods/CustomAlbums/files/15238608/temp.zip)

**Search by "name":**
![image](https://github.com/MDMods/CustomAlbums/assets/42017416/3b2fb0f3-9d19-4bfd-9979-d3e3daf2185d)

**Search by "name_romanized":**
![image](https://github.com/MDMods/CustomAlbums/assets/42017416/17f8c210-ba9a-4640-9360-b8e9a32b01a7)

**Comment by SB15-MD** [comment]
Fixed in [90a1dac](https://github.com/MDMods/CustomAlbums/commit/90a1dac9c5e69a70ffbac47ef5752fb4e41ce21c)
